### ISSUE TITLE
normal.survey broken

### ISSUE THREAD

**Issue by TimBock** [IQSS/Zelig#104]
I cannot replicate the example in http://www.idg.pl/mirrors/CRAN/web/packages/Zelig/vignettes/normal.survey.pdf.

When I run what I think is the code in the example, I get an error:

> data(api, package = "survey")
> z.out1 <- zelig(api00 ~ meals + yr.rnd, model = "normal.survey",weights = ~pw, data = apistrat)
Supplied weights argument is not a vector or a variable name in the dataset, and will be ignored.

Error in eval(expr, envir, enclos) : attempt to apply non-function

When I try and fix, I get a different problem, which seems incompatible with the purpose of normal.survey.

> z.out1 <- zelig(api00 ~ meals + yr.rnd, model = "normal.survey",  weights = apistrat$pw, data = apistrat)
Noninteger weights were set, but the model in Zelig is only able to use integer valued weights.
 A bootstrapped version of the dataset was constructed using the weights as sample probabilities.

Error in eval(expr, envir, enclos) : attempt to apply non-function

**Comment by tercer** [comment]
Tim,
If you are using version 5, normal.survey is not currently implemented in Zelig version 5.  However, it is now being implemented and should release with Zelig 5.0-10.  You can follow issue #70 for progress.  It has just gone up on a dev branch and should be in Beta by the end of the week.  I'll close this issue when this model is in production and live on the CRAN repository, and has documentation up on http://zeligproject.org.

**Comment by tercer** [comment]
The survey models {normal, poisson, logit, probit, gamma}-survey are now available on the Beta of Zelig 5.0-10.

The Beta is available from the IQSS repository as:
install.packages("Zelig", type = "source", repos = "http://r.iq.harvard.edu/")

Documentation for all the survey models is live on http://zeligproject.org for example, for normalsurvey: 
http://docs.zeligproject.org/en/latest/zelig-normalsurvey.html

This Zelig version is expected to go up on CRAN by Dec 31, 2015.

**Comment by tercer** [comment]
These models went up on CRAN as of Zelig 5.0-10 on March 14 (Pi Day).
