### ISSUE TITLE
setval doesn't appropriately handle logical values

### ISSUE THREAD

**Issue by enbrown** [IQSS/Zelig#106]
The function `setval` in Zelig/R/utils.R is called from `setx` (indirectly). It doesn't appear to handle logical values correctly which causes an error. For example, if treated is a boolean column:

`z5$setx1(treated = FALSE)`

results in the error:

`Error in setval(dataset[n[ma]][i][[1]], s[n[ma]][i][[1]]) : Wrong factor`

It appears as though the `setval` function is written expecting a numeric, ordered factor, or factor. So a logical column falls through the if/then statements and then fails when its interpreted as a factor.

**Comment by christophergandrud** [comment]
Thanks for reporting @enbrown. Should be implemented in f684d77d4937763cf76bee9eadb27866b12b97d2
