### ISSUE TITLE
normal.bayes appears to be broken in 5.0-8

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#108]
It appears that normal.bayes models are broken in the newest version of Zelig. For example, in the knitted documentation the model seems to fail: http://docs.zeligproject.org/en/latest/zelig-normalbayes.html. I get similar results on my own system.

**Comment by tercer** [comment]
Specifically, the model is estimating correctly, however the summary function is not producing useful results.  The issue appears to be that use of the dplyr functions are sometimes stripping the class of the result.  Without the class of the result, the wrong summary function is being applied.  This doesn't seem to happen for every model, but does happen for MCMCpack models that should give results of class mcmc.  

Here is a small sandbox example showing this behaviour:

![screen shot 2016-03-25 at 4 47 27 pm](https://cloud.githubusercontent.com/assets/2085037/14053737/c6ac65e4-f2a9-11e5-9531-7fef10d10347.png)

**Comment by tercer** [comment]
Now resolved.  For example, here is the summary output from the currently built docs at
http://docs.zeligproject.org/en/latest/zelig-normalbayes.html

<img width="864" alt="screen shot 2016-03-25 at 6 26 24 pm" src="https://cloud.githubusercontent.com/assets/2085037/14055308/4e012090-f2b7-11e5-9a7b-b4d9f701d77e.png">

Fix is up on GitHub and will go out to CRAN with Zelig 5.0-12, by the first week of April, and can be gotten immediately with:
library(devtools)
install_github('IQSS/Zelig')
