### ISSUE TITLE
Separate data package?

### ISSUE THREAD

**Issue by izahn** [IQSS/Zelig#112]
I'm slowing working on getting up to speed with the new Zelig package. A couple of things are making it more difficult than I'd like. One is that there are about 20 documented data sets distributed with the package, which clutters up the documentation and makes it harder to find function/class/method documentation. This could be improved by splitting out the data into a separate package, say `ZeligData` or `ZelegExamples`. Just a thought.

**Comment by christophergandrud** [comment]
This seems like a good idea. What are the current thoughts on this?

**Comment by izahn** [comment]
I think it's a good idea, but probably not high priority.

**Comment by christophergandrud** [comment]
I'm going to close this issue for the time being. I kind of worry that placing the data in another package would make package maintenance more cumbersome. However, if there is a burning case that develops to do this, feel free to reopen.
