### ISSUE TITLE
ZeligMultilevel

### ISSUE THREAD

**Issue by norakirk** [IQSS/Zelig#113]
I have run multi-level models in the newest version Zelig but, unfortunately, it did not work, I down graded Zelig and R - it did. However, commands for setting values and quantities of interest are still unable to fit the data.

**Comment by christophergandrud** [comment]
Hi @norakirk. Could you provide a self-contained reproducible example?

**Comment by christophergandrud** [comment]
I'm closing this do to a lack of reproducible example. Feel free to reopen when available.
