### ISSUE TITLE
R errors in documentation

### ISSUE THREAD

**Issue by rubenarslan** [IQSS/Zelig#115]
http://docs.zeligproject.org/en/latest/using-Zelig-with-Amelia.html

**Comment by tercer** [comment]
The code examples in the docs have been down since Monday Feb 15th, because of an issue installing Zelig on the Virtual Machine we are using.  Christine has been working on it, and I'll update this issue when it is resolved, hopefully quite shortly.

**Comment by pdurbin** [comment]
## Before

![using_zelig_with_the_amelia_package_for_missing_data_ _zelig_project_-_2016-02-23_14 32 33](https://cloud.githubusercontent.com/assets/21006/13264073/82873bc8-da3a-11e5-97da-33b64944d9d4.png)

## After

![using_zelig_with_the_amelia_package_for_missing_data_ _zelig_project_-_2016-02-23_14 33 41](https://cloud.githubusercontent.com/assets/21006/13264086/8bac17aa-da3a-11e5-930d-19c760c0f633.png)

Here was the fix (thanks to @cchoirat !): https://github.com/IQSS/zeligproject.org/commit/9bbcda590f0d4c7390fca539c0d86197f3f805e3
