### ISSUE TITLE
Error from coxph

### ISSUE THREAD

**Issue by danlewer** [IQSS/Zelig#143]
The cox's survival model appears to give an error, as explained in this stackoverflow post:

http://stackoverflow.com/questions/38134035/r-error-from-zeligs-coxph?noredirect=1#comment63699597_38134035

**Comment by christophergandrud** [comment]
Zelig 5 unfortunately doesn't support `coxph`. We'll be working on reintroducing support (https://github.com/IQSS/Zelig/issues/71)
