### ISSUE TITLE
Survey models not passing complex design to svyglm()

### ISSUE THREAD

**Issue by bgall** [IQSS/Zelig#144]
Based only my understanding of [Example 2](http://docs.zeligproject.org/en/latest/zelig-logitsurvey.html) from the survey model documentation, the initial model summaries of Zelig survey models should produce the same output as svyglm() from Thomas Lumley's 'survey' package. However, the zelig survey models do not appear to pass all of the complex design information to the underlying svyglm(). In particular, it appears that clustering may be overridden by hardcoding of "ids = ~1" as the clustering formula. There also may be an issue with the finite population correction.

A working example demonstrating the clustering and finite population correction issues can be found [here](https://github.com/Scientifiction/zelig-survey).

**Comment by christophergandrud** [comment]
`ids` is no longer hard coded `~1` from version 5.0-15 f1588859541d837db20e742f71196b6e74446881

Thanks for reporting this

**Comment by bgall** [comment]
@christophergandrud  I haven't had time to check the FPC, but it also appeared to occasionally not work. I am not opening an issue because I unfortunately don't have time to check and produce a reproducible example. Keep an eye out!

**Comment by christophergandrud** [comment]
Thanks. If you do encounter a problem please do open up an issue.
