### ISSUE TITLE
Median() in utils.R does not work

### ISSUE THREAD

**Issue by adamobeng** [IQSS/Zelig#148]
``` r
> Median(c(1,2,3))
Error in median(v) : object 'v' not found
```

This is because of a typo on line 31 of utils.R. Patch forthcoming.

**Comment by cchoirat** [comment]
Thanks Adam!

**Comment by adamobeng** [comment]
No problem, @cchoirat.

While I'm on the subject, can you confirm that this is the expected behaviour?

```
> Median(c(0, 10))
5
> Median(factor(c(0, 10)))
"10"
```
