### ISSUE TITLE
A number of bugs with average-related functions

### ISSUE THREAD

**Issue by adamobeng** [IQSS/Zelig#150]
@cchoirat : I have a patch ready to go which has unit tests and fixes for these, if you let me know which ones are bugs and which ones are expected behaviour.
## Mode() does not properly handle fixed-type vectors

```
> Mode(c('1', '1', 1, 1, 2, 2, 2))
[1] "1"
```

The correct result is 2
## Mode() does not maintain the ordered nature of ordered factors

```
> Mode(factor(c('a', 'a', 'b'), levels=c('b', 'a'), ordered=TRUE))
[1] a
Levels: b a
```

Should return an ordered factor.
## Mode() counts the labels of the factor, not the levels

I'm not sure if this is the intended behaviour:

```
> Mode(factor(c(1,1,2,2,3,3,3), levels=c(1,2,3), labels=c('a', 'a', 'b')))
[1] a
Levels: a a b
```

There are more 3s than either 1s or 2s, so if we were going by levels, the result
should be 'b'.
## avg() produces the mode of ordered factors which can be converted to numeric

I'm not sure if this is the intended behaviour:

``` r
> avg(factor(c(0,0,1,2,3)))
[1] 0
Levels: 0 1 2 3
```
## avg() produces incorrect results for ordered factor which can't be converted to numeric

``` r
> avg(factor(c('a', 'a', 'a', 'b', 'c', 'c', 'd'), ordered=T))
[1] b
```

I would have expected 'a', the mode.
## Median() produces unexpected values for factors which could be converted to numeric

``` r
> Median(factor(c(1, 2, 3, 4)))
"3"
```

I would have expected 2.5 given that there is an even number of values.

**Comment by cchoirat** [comment]
Thanks!  These utility functions were ported from previous versions of
Zelig, and factors have raised many issues in the past.  Let me run some
tests to see what is expected vs what is not.

**Comment by christophergandrud** [comment]
Sorry about the late reply @adamobeng . Do you still have the patch you mention up and running?

**Comment by adamobeng** [comment]
No worries, @christophergandrud. I think my patch got merged: https://github.com/IQSS/Zelig/pull/149
