### ISSUE TITLE
mode function

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#152]
Changes to the Mode() function in utils.R now give this warning everytime Zelig is loaded:

<img width="404" alt="screen shot 2016-11-04 at 11 19 34 am" src="https://cloud.githubusercontent.com/assets/2085037/20011091/d3cb32f0-a280-11e6-8e60-45b5ca50c2a4.png">

I believe this was added recently by Christine in concert with a user, to make Mode work as a setx() function in both upper and lowercase (I added roxygen2 support to add this to the last release).  Uppercase is the present Zelig norm, but lowercase was added for backwards compatibility.  Looks like lowercase is overwriting the base mode function.  We should see if there is a way around that, and if not, make a decision about what is best.  A warning every time the Zelig library attaches looks annoying.

**Comment by christophergandrud** [comment]
Implemented in 5.0-14:
