### ISSUE TITLE
Get R and Zelig back up on Jenkins

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#157]
A number of plugins are out of date on Jenkins, particularly SVN and Pipeline, and thus we can't get the latest R-devel up on Jenkins to test Zelig against for current CRAN checks.

**Comment by christophergandrud** [comment]
Moved CI testing to [Travis CI](https://travis-ci.org/IQSS/Zelig) and [Appveyor](https://ci.appveyor.com/project/christophergandrud/zelig).
