### ISSUE TITLE
Fix menu bar in docs.zeligproject.org 

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/Zelig#159]
The menu bar in the header of the http://zeligproject.org/ is not exactly the same as the menu bar in http://docs.zeligproject.org/en/latest/.  Could you update the menu bar in the docs (see menu list under Software) to match the one in zeligproject.org

**Comment by christophergandrud** [comment]
This will be resolved in the new [pkgdown versions of the documentation](https://github.com/IQSS/Zelig/tree/pkgdown).
