### ISSUE TITLE
Code test coverage

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#160]
Achieve code test coverage of at least 70%

**Comment by christophergandrud** [comment]
As part of this process, improve human-readable error messages.

**Comment by tercer** [comment]
I added about a dozen more Monte Carlo unit tests into the /testthat folder, here: 0905bf79e110e06f1cd4c63b83eb4a2947deec27 .  This is most of the models for which an `mcfun()` method for self testing has been defined. 

I see some issues with Weibull and Gamma models I'll look into further (they're not presently included in this batch) and review which models don't have `mcfun()` methods defined.

**Comment by christophergandrud** [comment]
@tercer Those are going in 5.0-14

**Comment by tercer** [comment]
Monte Carlo unit tests live for Weibull and Gamma models.

**Comment by tercer** [comment]
Tests for getters,  several utilities (like `createJSON()`, refererences), MCMC diagnostics and simple tests for plot completion up.

**Comment by tercer** [comment]
Some tests for timeseries and weights and ROC curves.  That's likely the end of my test additions for present.

**Comment by christophergandrud** [comment]
Really excellent work. Thanks so much!

**Comment by christophergandrud** [comment]
I'm closing this for the time being. But it's clearly an ongoing process.
