### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#174]
Just wondering about the version numbering system that Zelig uses. How closely does it correspond to [semantic versioning](http://semver.org/), e.g. MAJOR.MINOR.PATCH 

It seems like currently Zelig uses: MAJOR.?-MINOR. Am I missing something?

**Comment by pdurbin** [comment]
@christophergandrud now you've got me wondering about why there's nothing under https://github.com/IQSS/Zelig/releases which corresponds to tags in Git. I suppose the way to see a list of prior versions is to visit https://cran.r-project.org/src/contrib/Archive/Zelig/ rather than looking at Git tags. Anyway, I imagine http://docs.zeligproject.org/en/latest/devguide.html would be the place to explain the version numbering but I don't see anything there.

**Comment by christophergandrud** [comment]
Side note on git tags: I'm not really a big fan of them for R packages. I think they make more sense for software for which there is no obvious external service like CRAN to release them through. Otherwise they often become redundant and haphazardly used (at least in my experience).

**Comment by tercer** [comment]
My sense would be that with say release 5.0-13, that is read as
Major(Version) 5, Minor 0, Patch 13.    We're 13 patches into getting Zelig
version 5 up.  I realize our "patches" are much broader than the typical
usage and generally add functionality as well as provide fixes.

My sense with some R package users is that they see a minor version
increment as suggesting they need to relearn or restudy the package, and
"minor" increments are useful for signalling some milestone or broad set of
features has been accomplished.  Probably R users take the lead from R
itself, which releases about a "patch" a month, and and "minor" increment
every year, even though there's often strictly functionality improvements
between patches.

**Comment by christophergandrud** [comment]
Thanks, that's pretty much what I thought, but just wanted to make sure.

I'm thinking that at least while I'm working on Zelig's internals intensively we could define PATCH more narrowly and aim for more frequent CRAN releases. A lot of the bigger features that are [now listed](http://zeligproject.org/releases-roadmap) under 5.0-14 could be moved to a 5.1 release. Does that sound ok?
