### ISSUE TITLE
lsmixed not estimated

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#179]
The `lsmixed` model seems to not work at all. E.g. the error in the documentation: http://docs.zeligproject.org/en/latest/zelig-lsmixed.html

**Comment by cchoirat** [comment]
Mixed models docs are mostly placeholders at the moment.

**Comment by christophergandrud** [comment]
Ah, I see that there is no `model-lsmixed` in the package. 

At least Zelig now returns a the error: `lsmixed is not a supported model type.` from the wrapper and `Error: object 'zlsmixed' not found` if trying to use it in Zelig 5 syntax (not the most informative error message, but I'm not sure how we can improve it).
