### ISSUE TITLE
Average Treatment Effects broken between versions 5.0-13 and 5.0-14

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#194]
Average Treatment on the Treated is a quantity of interest available for certain models.  It works in Zelig_5.0-13 but breaks in Zelig_5.0-14, and seems to be related to changes in `z$simparam`

Here is it working:
<img width="534" alt="screen shot 2017-02-03 at 9 04 57 pm" src="https://cloud.githubusercontent.com/assets/2085037/22614772/3c173266-ea55-11e6-8002-e5dc7d760322.png">

Here is it failing:
<img width="537" alt="screen shot 2017-02-03 at 9 07 25 pm" src="https://cloud.githubusercontent.com/assets/2085037/22614776/445253ca-ea55-11e6-86eb-f616ac48c341.png">

Here is the 5.0_13 `z$simparam` object:
<img width="262" alt="screen shot 2017-02-03 at 9 05 42 pm" src="https://cloud.githubusercontent.com/assets/2085037/22614781/5ddcc960-ea55-11e6-9045-188ad19da2bf.png">

Here is the 5.0_14 `z$simparam` object:
<img width="290" alt="screen shot 2017-02-03 at 9 07 50 pm" src="https://cloud.githubusercontent.com/assets/2085037/22614782/61d043e4-ea55-11e6-9450-2099d42c76d3.png">

**Comment by christophergandrud** [comment]
The issue has to do with the new use of deep assignment for `num`.

I reverted it back and completed the tests for this bug in: 31379643f1aaca5660b1dee20766fa705c86a4cb
