### ISSUE TITLE
assertion is_simsrange

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#204]
The `ci.plot()` graph is used both for ranges and for graphing certain timeseries quantities of interest.  The `is_simsrange` assertion is being tripped when these timeseries qi's are sent for graphing, breaking qi plots.

I've fixed this right now, by exempting from this assertion when `'timeseries' %in% obj$category`, which is a good way to know if a model is a timeseries, in this commit: 72e22fcdfbea26bd39a73eeae2b4fc71a7f6b44e

However, [1] there are likely more precise tests for whether the timeseries qi's are correctly set up for a ci.plot style graph and [2] perhaps `timeseries` membership ought to be built into the `is_simsrange` assertion directly, rather than bypassing it.  The latter really depends on the meaning and intention of the assertion test.

So the bug in plotting timeseries qi's is fixed, but I'm open for discussion of further elaboration of this check.

**Comment by christophergandrud** [comment]
Thanks for catching this. 

In all cases where `is_simsrange` is used (in plot and graph) we would want to know this information.  So I would think we should include this in the assertion function and probably rename it. How about `is_simsrange_or_timeseries`. 

Implementing now . . .

**Comment by christophergandrud** [comment]
After playing around with some possibilities, I think creating a separate `is_timeseries` assertion makes more sense, i.e.:

```r
if(!is_timeseries(obj)) is_simsrange(obj$sim.out)
```

This can then also be used at other points throughout `plot` and related functions.

Added in: 10c7f61d4332cb9c3383191e5b332547b7fef57c
