### ISSUE TITLE
Inappropriate plots generated for quantities of interest for mlogitbayes model

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#206]
Plots of qi's for `mlogitbayes` are inappropriate to a multinomial variable.  However, plots for `mlogit` in the ZeligChoice package, which uses the same plot routines, are correct.  So some fix is needed either in the field definitions of `mlogitbayes` or the internal logic of `simulations.plot`.

**Comment by tercer** [comment]
The underlying issue is the expected values generated by mlogitbayes are 3-dimensional arrays as opposed to matrices, and `simulations.plot()` doesn't recognize what to do with them, so runs default behaviour.  

Am working out whether to make `simulations.plot()` more flexible, or adjust the `$qi()` method for the  `mlogitbayes`  model.

**Comment by tercer** [comment]
The same structure (3-dimensional arrays as output for expected values) is also found in `oprobitbayes`.

**Comment by tercer** [comment]
The array structure is present in Zelig 3.5, and seems to have been ported directly.  

@cchoirat:  What are the circumstances under which the model matrix `mm` would have multiple lines in the `qi` call, given how we presently use `dplyr`?  Is the possibility of a multiple line `mm` simply vestigial to Zelig 3.5?

I see you thought a bit about this here:
https://github.com/IQSS/Zelig/blob/master/R/model-oprobit-bayes.R#L66
https://github.com/IQSS/Zelig/blob/master/R/model-oprobit-bayes.R#L84-L85

Can I just rewrite the `qi`'s to assume the `mm` argument is one row?

**Comment by cchoirat** [comment]
@tercer: there are no examples of model matrices with multiples rows.  I
kept them from Zelig 3.5 and 4 thinking they'd be useful at some point.
Never ran into a concrete case though.

**Comment by tercer** [comment]
Given @cchoirat 's message, an immediate fix is now up here: https://github.com/IQSS/Zelig/commit/aa02a84ab8680169be0e29ac019a70a1d8113a4c

I'll work through though to create a more comprehensive review to pare down the code for the QI's and also make it more readable.

**Comment by tercer** [comment]
Example of fix up on model page for zeligproject.org:

<img width="595" alt="screen shot 2017-03-02 at 6 30 45 pm" src="https://cloud.githubusercontent.com/assets/2085037/23531856/876ec554-ff76-11e6-9927-6a9e805f6581.png">

**Comment by christophergandrud** [comment]
Looks good. I tested it out and updated the NEWS in 5ad8051fc0cf2b6420f2d585e636fd576576ae84

Is there anything else we need to do to close this?

**Comment by tercer** [comment]
I'm still planning to rewrite the qi functions.  Should get to this week.

**Comment by christophergandrud** [comment]
I'm going to close this issue. Rewriting the `qi` functions seems like a separate issue.
