### ISSUE TITLE
Demos vs. vignettes

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#217]
Based on [Hadley's advice](http://r-pkgs.had.co.nz/demo.html) and the new documentation framework based on pkgdown--which works with vignettes rather than demos, we may want to consider moving the demo material into vignettes.

**Comment by cchoirat** [comment]
Totally on board!

**Comment by christophergandrud** [comment]
Cool. I'm storing the demos in this repo for the time being: https://github.com/IQSS/zelig-demos

**Comment by cchoirat** [comment]
Actually, most demos were used for test purposes.  Glad you put them in
another repo.
