### ISSUE TITLE
Zelig support for two-stage least squares

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#223]
Hi @cchoirat and @tercer. I have a question over at the Zelig email address regarding support for instrumental variable regression. Looking through the docs it looks like the answer currently is no. 

Am I missing something? If not, then this seems like something we could easily add to the Road Map.

**Comment by cchoirat** [comment]
Correct, it's not supported (neither is 3SLS) and could be added to the
roadmap.

**Comment by christophergandrud** [comment]
Sounds good. I've added it. to the roadmap.

**Comment by tercer** [comment]
Obviously entangled with #128

**Comment by christophergandrud** [comment]
Section 5 of the [Formula package vignette](https://cran.r-project.org/web/packages/Formula/vignettes/Formula.pdf) may provide some guidance here if we chose to use the **Formula** package.

**Comment by christophergandrud** [comment]
Basic working version of IV regression working: https://github.com/IQSS/Zelig/tree/ivreg

This wraps `ivreg` from AER (which Zelig already imports for `tobit`). `ivreg` uses Formula formulas. 

It looks like it breaks the formula transformer I had for logs and factors. So I need to fix that. Also need to think about quantities of interest.
