### ISSUE TITLE
get_coef/get_se: Return combined results when using MI dataset to estimate model

### ISSUE THREAD

**Issue by vincentarelbundock** [IQSS/Zelig#229]
Currently, ``get_coef`` and ``get_se`` return individual models' values when multiple imputation is used. Would be useful to have an option to return combined estimates instead (perhaps even by default).

```
library(mice)
library(Zelig)
library(Amelia)
data(nhanes)
a.out <- Amelia::amelia(nhanes, p2s=0, m=2)
m.out <- Zelig::zelig(age ~ chl, model='poisson', data=a.out)
m.out$get_se()

[[1]]
(Intercept)         chl 
0.716286552 0.003396207 

[[2]]
(Intercept)         chl 
0.554528967 0.002454642 
```

**Comment by christophergandrud** [comment]
That's a good idea. 

I think the option to combine probably wouldn't be by default as the `get_*` functions are mostly for internal use. Thoughts @tercer and @cchoirat?

**Comment by vincentarelbundock** [comment]
A simple and better (?) solution might be to create a ``rubin_rules`` function similar to ``pool`` in the ``mice`` package. For instance:

```
rubin_rules = function(coeflist, vcovlist=NULL){
    # coefficients
    q <- do.call('rbind', coeflist)
    am.m <- nrow(q) # number of imputed datasets
    am.k <- ncol(q) # number of estimated coefficients per model
    ones <- matrix(1, nrow = 1, ncol = am.m)
    imp.q <- (ones %*% q) / am.m # Slightly faster than "apply(b, 2, mean)"
    # standard errors
    if(!is.null(vcovlist)){
        selist = lapply(vcovlist, function(k) sqrt(diag(k)))
        se <- do.call('rbind', selist)
        ave.se2 <- (ones %*% (se^2)) / am.m # Slightly faster than "apply(se^2, 2, mean)"
        diff <- q - matrix(1, nrow = am.m, ncol = 1) %*% imp.q
        sq2 <- (ones %*% (diff^2)) / (am.m - 1)
        imp.se <- sqrt(ave.se2 + sq2 * (1 + 1 / am.m))
    }else{
        imp.se <- NULL
    }
    out <- list('q'=as.vector(imp.q), 
                'se'=as.vector(imp.se))
    return(out)
}
```

Example: 

```
library(mice)
library(Amelia)
library(Zelig)
imp <- amelia(nhanes)
mod <- zelig(age ~ hyp, data=imp, model='poisson')
coeflist = mod$getcoef()
vcovlist = mod$getvcov()
```

This produces the same result as current Zelig:

```
> rubin_rules(coeflist, vcovlist)
$q
[1] -0.1277376  0.5441133

$se
[1] 0.4857452 0.3468233

> summary(mod)
Model: Combined Imputations 
            Estimate Std.Error z value Pr(>|z|) 
(Intercept)  -0.1277    0.4857  -0.263   0.7926 
hyp           0.5441    0.3468   1.569   0.1167 
---
Signif. codes:  '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

Bonus: With some minor tweaks, you could improve the function to remove code duplication (see #-comment at the second link):

https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L786
https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L826

**Comment by tercer** [comment]
In terms of code reuse, two quick points.  The origin of this code is the *mi.meld()* function from Amelia:

https://github.com/IQSS/Amelia/blob/master/R/diag.r#L766-L808 

So possibly we can either copy that into Zelig utils or attach.

Second, as to the point of code duplication, the se's in the bootstrap case are different than Rubin's rules, which is not a difficult problem to overcome, but requires some thought about whether you want a function that does everything, or a function for imputed results (Rubin's rules).

**Comment by christophergandrud** [comment]
It seems like it may make sense to have one function in Zelig utils that can combine results from models when using multiple imputation or bootstrap. Using code currently in 

https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L786

or

https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L826

when appropriate.

Maybe with the name `combine_coef_se`? 

I would imagine that the main use of this would be as an option when calling `get_coef` or `get_se`. So an argument to these methods could be added, something like `combine_coef` and `combine_se`. These would call `combine_coef_se`. They would be set as `FALSE` by default to avoid breaking current Zelig usage.

Does that make sense?

**Comment by christophergandrud** [comment]
85ece9afc2d75bd3d5f934fffd834fd5d39f330f implements `combine_coef_se`. See: https://github.com/IQSS/Zelig/blob/master/R/utils.R#L440-L542 

`combine_coef_se` takes as input a Zelig estimated function model with MI and/or bootstrapping and returns a list containing the combined coefficients, standard errors, z and p values. For example:

```r
library(mice)
library(Amelia)
library(Zelig)
imp <- amelia(nhanes)
mod <- zelig(age ~ hyp, data = imp, model = 'poisson')

combine_coef_se(mod)

## Combining imputations. . .
## $coef
## (Intercept)         hyp 
##  -0.1437463   0.5437551 
## 
## $se
## (Intercept)         hyp 
##  0.4901188   0.3416864 
## 
## $zvalue
## (Intercept)         hyp 
##  -0.2932888   1.5913865 
## 
## $p
## (Intercept)         hyp 
##   0.7693014   0.1115226 
```

Note it replicates `zelig` `show`s current behaviour where if a model with *both* MI and bootstrapping is entered it uses Rubin's Rules to combine the quantities.

This function allowed me to streamline the `show` code somewhat. We now have just: https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L786-L813

## Outstanding issues:

- The reason I included all 4 of these quantities is that it seems like this could go a long way to making texreg work with MI and bootstrapping, e.g. https://github.com/leifeld/texreg/pull/29#issuecomment-283420550

- Does the name--`combine_coef_se`--work?

- @tercer do you have a handy citation for the combination rules you used for bootstrap?

    + @tercer (and maybe @mattblackwell) might be worth doing some documentation/publicity with Zelig + Amelia with a working texreg example when that is up. Seems like this would really make Amelia outstanding for a reproducible literate programming workflow.

**Comment by cchoirat** [comment]
That's great!

Have you tried printCoefmat in
https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L786-L813?

**Comment by christophergandrud** [comment]
@cchoirat that's a good idea. Trying now. . .

**Comment by vincentarelbundock** [comment]
Out of curiosity (now that you're looking at this stuff), what's the recommended way to to extract the 4 sets of statistics produced by ``combined_coef_se`` in regular, non-MI models? I see a ``getcoef()`` and a ``getvcov()``, but no ``getp``, for example.

Would it be possible to allow users to capture the output of ``show()``?

When dealing with ``lm`` objects, I'll sometimes summary(model)$coefficients to get a clean set of results.

Internally, this is also what ``texreg``'s extract functions also do.

**Comment by christophergandrud** [comment]
@vincentarelbundock Yeah, I was thinking about that too.

There is a `get_pvalue`, but not `get_zvalue`.

Before embarking on this, what is the advantage over `z$get_*()`?

**Comment by cchoirat** [comment]
Great (#166)

**Comment by vincentarelbundock** [comment]
I was having issues the other day with ``get_pvalue()``, but that appears to have been user error, since it works now.

I suppose there's not much added relative to the ``get_*()`` beyond convenience and conformity of user experience across Zelig and base R.

When ``coef(model)`` and ``summary(model)$coefficients`` both failed, I had to look at ``str()`` before I could find ``model$get_coef()``. Call me lazy, but I don't like reading docs if I can avoid it, so this was a turn-off for me as a new Zelig user.

**Comment by christophergandrud** [comment]
@vincentarelbundock That is a good point regarding ease of use.

**Comment by vincentarelbundock** [comment]
sorry to keep coming up with ideas for other people to execute, but wouldn't it be easy to create some sort of alias for ``coef(mod)`` to trigger ``mod$get_coef()``?

**Comment by vincentarelbundock** [comment]
In general, it just seems like facilitating the use of idiomatic R expressions would be a good thing.

**Comment by christophergandrud** [comment]
This does exist: https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L1418-L1424

Though seems be broken.

**Comment by christophergandrud** [comment]
Opened a new issue: https://github.com/IQSS/Zelig/issues/231

**Comment by christophergandrud** [comment]
Note that the default behaviour (from 3f74a0d9102ea3e7e37588449634b475fa02a2ab) is to return a matrix rather than a list. Though a list can still be returned with `out_type = "list"`.
