### ISSUE TITLE
ZeligChoice: get_qi has broken plot method

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#230]
The plot method for ZeligChoice has broken with the latest Zelig release as it can not find the newly renamed get_qi internal.  My assumption is this is the same logic as issue #187 .  That was fixed by bumping up the Zelig dependency.  So I'll up the dependency, and we should push ZeligChoice to CRAN again.

Examples follows:
<img width="675" alt="screen shot 2017-03-01 at 3 41 51 pm" src="https://cloud.githubusercontent.com/assets/2085037/23480551/4c27aa32-fe96-11e6-9d6e-066fe78b329a.png">

As a general issue, we should think about folding the ZeligChoice tests more automatically into the Zelig build tests, and remember to increase the dependency in ZeligChoice (and push to CRAN) every time we significantly change the Zelig internals that are being inherited (which is most releases right now given the present emphasis).

**Comment by christophergandrud** [comment]
Looks like ZeligChoice is ready to go. Should I push it to CRAN now?

**Comment by tercer** [comment]
Sure.  I was following up on multinomial plots before pinging you for this, but that is not looking like having any consequences for ZeligChoice.  

Also, to confirm, the issue is indeed fixed with this dependency update.

**Comment by christophergandrud** [comment]
Great! I'll push the updated version to CRAN now  . . .
