### ISSUE TITLE
ATT and simATT documentation

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#245]
It looks like `ATT` and `simATT` are undocumented.

Is there any documentation already around in a different location that I'm missing that I could use to begin building this?

**Comment by tercer** [comment]
There is now the smallest piece at the bottom of the getters documenation ( http://docs.zeligproject.org/en/latest/getters.html ), and as soon as #253 is resolved, I'll add an section specifically about ``ATT``.

**Comment by christophergandrud** [comment]
fyi: `ATT` wrapper added

**Comment by christophergandrud** [comment]
Should we import this vignette into the Zelig site and update the syntax? https://r.iq.harvard.edu/docs/matchit/2.4-15/Examples2.html

Seems like it is as much about Zelig as MatchIt and would be good to point to.
