### ISSUE TITLE
Bivariate probit error: list function doesn't work

### ISSUE THREAD

**Issue by shrabasteebanerjee** [IQSS/Zelig#248]
Hi,

I have been trying to run a bivariate probit using both reference classes and wrappers (following the syntax here: http://ftp.uni-bayreuth.de/math/statlib/R/CRAN/doc/vignettes/Zelig/bprobit.pdf and here for reference classes: http://docs.zeligproject.org/en/latest/zeligchoice-bprobit.html), but it doesn't work:

[Y1 = more_than_2
Y2 = divorced
X's = same_sex, Y1,...(other controls not mentioned in this example)]

> formula <- list(mu1 = more_than_2 ~ same_sex, mu2 = divorced ~ more_than_2)
 >zelig1 <- zelig(formula, model = "bprobit", data = ae)
>"Error in formula.default(object, env = baseenv()) : invalid formula"

I wondered if this was because Zelig somehow did not support Y1 being fed into Y2, but it doesn't work even if I want to estimate Y1 and Y2 for the same X:

 >formula <- list(mu1 = more_than_2 ~ same_sex, mu2 = divorced ~ same_sex)
> zelig1 <- zelig(formula, model = "bprobit", data = ae)
>"Error in formula.default(object, env = baseenv()) : invalid formula"

Same in this case:

> z5 <- zbprobit$new()
> z5$zelig(list(mu1 = more_than_2 ~ same_sex, mu2 = divorced ~ more_than_2), data = ae)
Error in formula.default(object, env = baseenv()) : invalid formula

I have also included rho = ~1 in the formula, but that doesn't work either. 
If I use cbind (divorced, more_than_2) ~ X's, that works, but since I need the Y1 and Y2 to be estimated for different explanatory variables, I need to use the "list" function as specified in the vignette. Could you let me know what I'm doing wrong? Thanks.

**Comment by christophergandrud** [comment]
Hi @shrabasteebanerjee 

Unfortunately, support for multiple right-hand side equations was removed in Zelig 5. So you would not be able to estimate this model. We are slowly trying to reintroduce these capabilities.

**Comment by shrabasteebanerjee** [comment]
Thanks very much for your response! Just out of curiosity, might you be
aware of packages on R that have this functionality?

Best,

Shrabastee

**Comment by christophergandrud** [comment]
Sorry I don't (I don't use these models in my research so haven't really looked.)

**Comment by henrykironde** [comment]
@shrabasteebanerjee, did you find a package that runs bprobit

**Comment by shrabasteebanerjee** [comment]
Hey Henry - unfortunately not, I think you would have to code it up :(
