### ISSUE TITLE
ZeligGAM: as.Formula breaking all the GAM models

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#251]
All of the GAM models are breaking because as.Formula is missing.

<img width="875" alt="screen shot 2017-04-12 at 6 21 36 pm" src="https://cloud.githubusercontent.com/assets/2085037/24982066/908d5180-1fad-11e7-8bc5-650420d6d690.png">

My guess is this is a result of internal changes to the Formula use.

I realize this package is under development, but when it breaks the docs on zeligproject.org, it breaks docs that follow in strange ways.  For now, I've set EVAL=FALSE for all GAM models on the docs.  It might make sense to remove them until we have a GAM package that is released.

**Comment by christophergandrud** [comment]
Hm would it make sense to have the Zelig docs built from the released rather than development version of Zelig?

**Comment by tercer** [comment]
The comment "under development" was really a reference to ZeligGAM, not Zelig itself.  From my perspective, I've found it useful to be able to write the docs at the same time as developing features, see issues that break in the examples, and then fix them live in the code.  However, pegging the docs to a stable release has been on the wishlist of @cchoirat .

Also, seeing the docs break has often served as a canary for some issue in changing the code, however, the current expanded code coverage is certainly a more formal approach to this.  At some point, it would be clever to include the docs building successfully as part of the code coverage suite (although the docs examples take about 8 minutes on their own.)

**Comment by christophergandrud** [comment]
This is really a case study in why the docs should be written with the package locally in line with roxygen and then not pushed publicly, including to the website, until they have passed all tests (8 minutes is a long time, but better than having the front facing docs be broken).

I was holding off on this process until NaLette came and OpenScholar figured out whatever it is that they need to figure out, but maybe we should shift our focus to starting this now. (Which I guess would mean holding off on OpenScholar integration until the future).

**Comment by christophergandrud** [comment]
Formula added in https://github.com/IQSS/ZeligGAM/commit/68bf9ece628c335e550506bcb7c2046a192e679b
