### ISSUE TITLE
Zelig getter docs broken

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#253]
Example at Zelig docs-- http://docs.zeligproject.org/en/latest/getters.html --returning error:

<img width="301" alt="screen shot 2017-04-13 at 07 28 36" src="https://cloud.githubusercontent.com/assets/1285805/24991408/da48dcc8-201a-11e7-8fe7-8c6f3bb2bd67.png">

I'm not actually able to reproduce the error locally:

```R
library(Zelig)

data(sanction)
zqi.out <- zelig(num ~ target + coop + mil, model = "poisson", data = sanction)

zqi.out$setx(coop = 1)
zqi.out$setx1(coop=4)
zqi.out$sim()
```

Works fine with the current master build 4750fbcf1c92c8d24f61dec512b8af0d5ea62925

**Comment by christophergandrud** [comment]
This is especially perplexing because the model was definitely estimated. The screenshot above is preceded by:

<img width="465" alt="screen shot 2017-04-13 at 07 49 37" src="https://cloud.githubusercontent.com/assets/1285805/24991819/ed76159c-201d-11e7-837c-2d13ec053804.png">

**Comment by tercer** [comment]
I was looking into this for a little while, and then put up on the doc issue queue (https://github.com/IQSS/docs.zeligproject.org/issues/16) as you saw.  The example is fine, and runs in both Zelig 5.0-17 and 5.1-0.  In fact it's the same example that runs without a problem on the poisson model page.  The bootstrap documentation that comes next has the same issue:

<img width="871" alt="screen shot 2017-04-13 at 10 50 49 am" src="https://cloud.githubusercontent.com/assets/2085037/25010118/1ad9805a-2037-11e7-82ea-508c67f5f6a3.png">

In the past, these kinds of issues have been that some example that is broken upstream in the documentation is causing issues to examples that follow.  So I've been working through the breaking examples in the models section (https://github.com/IQSS/docs.zeligproject.org/issues/15 https://github.com/IQSS/docs.zeligproject.org/issues/17 #251 #252 ).  I'll keep at it.

**Comment by tercer** [comment]
There's an error of this type all the way back in the Quickstart guide:

<img width="882" alt="screen shot 2017-04-13 at 3 17 24 pm" src="https://cloud.githubusercontent.com/assets/2085037/25020484/9127daac-205c-11e7-8295-705517e2da0c.png">

**Comment by tercer** [comment]
See also https://github.com/IQSS/docs.zeligproject.org/issues/18

**Comment by christophergandrud** [comment]
Are the Sphynx builds version controlled? It would be nice to be able to figure out when this all started, especially since we can't replicate it locally.

**Comment by tercer** [comment]
No.  But it does build a pdf (that no one has access to https://github.com/IQSS/docs.zeligproject.org/issues/5 ) which we could easily be storing.

**Comment by christophergandrud** [comment]
This issue is resolved in the new docs (temporary URL: https://christophergandrud.github.io/Zelig/articles/getters.html)

I'm also going to add in some examples from the Google Groups discussion: https://groups.google.com/forum/#!topic/zelig-statistical-software/B3lhSwsvwsw
