### ISSUE TITLE
Setx breaking for exp model

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#254]
The ``setx`` method is throwing up errors in the ``exp`` model.  This was mentioned on the docs queue too ( https://github.com/IQSS/docs.zeligproject.org/issues/15 )  but seems to be an actual code problem, and not a Sphinx/VM issue.

<img width="501" alt="screen shot 2017-04-13 at 1 18 36 pm" src="https://cloud.githubusercontent.com/assets/2085037/25016003/47051e68-204c-11e7-8d0a-a60e228f3cda.png">

**Comment by christophergandrud** [comment]
Need to load the suvival package, e.g. 83bf6c6cb3a76faf0dad42dce3f0748a866615b0

**Comment by christophergandrud** [comment]
Need to think of a more elegant solution, but closing for now.

**Comment by tercer** [comment]
One solution is to upgrade the `survival` package to `Depends` to make sure it is attached rather than just loaded.  Here is it working in this example:

<img width="687" alt="screen shot 2017-04-19 at 3 44 09 pm" src="https://cloud.githubusercontent.com/assets/2085037/25199100/ac86ba56-2517-11e7-9b37-fd0a0a2026f2.png">

Here's a patch with that solution if that works for now: 375d2efb5eb4d60d867b8a8967af194d9dd6d58a

**Comment by christophergandrud** [comment]
Patch merged into master in d865edcbdc31f43649e5052533fdd666443bf367

And docs updated in: https://github.com/IQSS/docs.zeligproject.org/commit/5a0756c88dcff679176f716a25b1ff51a5d75630
