### ISSUE TITLE
Quantile model broken

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#255]
The example in the docs for calling a ``quantile`` model appears to be broken.  

<img width="460" alt="screen shot 2017-04-13 at 2 15 29 pm" src="https://cloud.githubusercontent.com/assets/2085037/25018032/df2f0d0a-2053-11e7-89b3-28a9fce25b5f.png">

**Comment by christophergandrud** [comment]
`rbind_all` issue addressed in f4e32b4da530f14bc50712f0a484f7de8b99b15b

**Comment by christophergandrud** [comment]
Seems to work if `tau` isn't explicitly specified, e.g.:

```r
z.out <- zelig(stack.loss ~ Air.Flow + Water.Temp + Acid.Conc.,
                      model = 'rq', data = stackloss)

summary(z.out)
## Model: 
## 
## Call: z5$zelig(formula = stack.loss ~ Air.Flow + Water.Temp + Acid.Conc., 
##     data = stackloss)
## 
## tau: [1] 0.5
## 
## Coefficients:
##             coefficients lower bd  upper bd 
## (Intercept) -39.68986    -41.61973 -29.67754
## Air.Flow      0.83188      0.51278   1.14117
## Water.Temp    0.57391      0.32182   1.41090
## Acid.Conc.   -0.06087     -0.21348  -0.02891
## Next step: Use 'setx' method
```

**Comment by christophergandrud** [comment]
Fixed for `tau` of length 1 in 69957ba074009a3249586339206168eaa24c29ff with tests.

The issue persists for `tau` of greater than length 1, which is documented in: http://docs.zeligproject.org/en/latest/zelig-quantile.html

**Comment by christophergandrud** [comment]
Some thoughts in this branch: https://github.com/IQSS/Zelig/commit/9e1654dfac5344af212368bd085b49ceee33eb06

Is there any documentation on this `rse`: https://github.com/IQSS/Zelig/blob/master/R/model-quantile.R#L57

**Comment by tercer** [comment]
Here's when ``tau`` became a ``by`` variable: https://github.com/IQSS/Zelig/commit/fe632f23b42aea7d6c7188d4b9b0d855d0c396d4#diff-8224f3ab9d3ff85ddc2436ab3bf76e8e

Not sure what it is accomplishing?

**Comment by tercer** [comment]
Updated the quantile doc example with ``tau``>length 1, to specify the dataset location.

**Comment by christophergandrud** [comment]
Did some more digging. I am not sure how this worked from being ported over to Zelig 5. However, for the time being, Zelig returns an error for tau length > 1: b13b20d448a3990b79f6d3a5e10517b67eb3e1ea.

It basically now works through until `plot`, but more work needs to be done on the quantities of interest.

**Comment by christophergandrud** [comment]
I'll update the docs.

**Comment by christophergandrud** [comment]
Docs updated in: https://github.com/IQSS/docs.zeligproject.org/commit/03d1889569510356e78ea2dc4f17299997575b40
