### ISSUE TITLE
Confidence interval from relogit regression

### ISSUE THREAD

**Issue by cchoirat** [IQSS/Zelig#259]
Received via email:

I am using Zelig for rare event logistic regression. I am conducting the following regression in R:

```r 
invlogit <- function(x){1/(1+exp(-x))}
beta_0 <- -7
beta_1 <- 1
x <- rnorm(100,0,1)
U <- runif(100,0,1)
y <- as.numeric(invlogit(beta_0 + beta_1*x) > U)
 
library(tidyverse)
data <- tibble(x,y)
 
Logit3 <- zelig(y~x,model = "relogit", tau = mean(y),
                case.control = c("prior"),bias.correct = TRUE,data  = data)
```
 
How do I pull confidence interval for beta_0 and beta_1 from the relogit regression? and how do I estimate for example the P(Y =1/X =some value).

**Comment by christophergandrud** [comment]
Hello emailer. 

First thing, in your example you supply `tau = mean(y)`. Here `mean(y) = 0`. However, `tau` should be the true proportion of  "1"s in the outcome. So it can't be zero. If it is then there isn't much point estimating the model and it will return an error. Though admittedly we could make the error more informative. 

Second, there isn't a built in function at the moment for relogit to return the confidence intervals of the parameter estimates. However, you can extract all of the info you need from `Logit3` to find the confidence intervals with the standard formula:

```r
coefs <- coef(Logit3)
se <- sqrt(diag(vcov(Logit3)[[1]]))
```

Please see the Relogit documentation for examples of how to estimate the predicted values: http://docs.zeligproject.org/en/latest/zelig-relogit.html
