### ISSUE TITLE
Zelig 4 compatibility wrapper doesn't work for ARIMA models

### ISSUE THREAD

**Issue by mbsabath** [IQSS/Zelig#280]
Code ran:
```r
data(seatshare)
subset <- seatshare[seatshare$country == "UNITED KINGDOM",]
z.out <- zelig(formula = unemp ~ leftseat, order = c(1,0,1), model = "arima", data = subset)
```
Output:
`Error: arima is not a supported model type.`

**Comment by christophergandrud** [comment]
As a first step I updated the docs to indicate that the wrappers don't work for `arima` (or `ma`): a2af2e4005a11e69d9177e67b0b91f61046ee6ac

I've been trying to work on a solution to this, but it is taking a bit of effort to figure out how the timeseries wrappers work. . .

**Comment by christophergandrud** [comment]
Resolved in https://github.com/IQSS/Zelig/pull/289
