### ISSUE TITLE
Zelig ARIMA, AR, and MA models may be redundant

### ISSUE THREAD

**Issue by mbsabath** [IQSS/Zelig#284]
Is there any reason we have separate AR, MA, and ARIMA models? AR and MA are both just special cases of ARIMA, and having a single ARIMA type function would likely be easier for users. Looking at the code, from what I can tell, the only difference between them is that using the AR and MA models automatically sets the order to be `c(1,0,0)` or `c(0,0,1`) respectively.

**Comment by christophergandrud** [comment]
I'm leaning towards having one `timeseries` model where a user could set `model = 'ar'` or `model = 'ma'` for convenience.
