### ISSUE TITLE
Stray "$$"s in some online vignettes

### ISSUE THREAD

**Issue by mbsabath** [IQSS/Zelig#285]
Found one instance of this issue in the vignette for the standard Gamma regression. I took a look at the Rmd file, and the solution isn't immediately apparent.

**Comment by christophergandrud** [comment]
Yep some of those exist. `$$` opens or closes a display equation in Rmarkdown. We just need to make sure that every `$$` that is opened is correctly closed with another `$$`

**Comment by mbsabath** [comment]
Fixed it in Gamma. I'm going to comb through the other vignettes now to see what others have the problem.

**Comment by mbsabath** [comment]
normal-gee has issues in the online vignette, but the Rmd code doesn't match the html. Maybe pkg-down hasn't been run recently?

**Comment by mbsabath** [comment]
All others cleaned up, minus normal-gee. pushing the changes to the Doc Update branch now.
