### ISSUE TITLE
sim method returns error for AR and MA models

### ISSUE THREAD

**Issue by mbsabath** [IQSS/Zelig#287]
going through the examples in the arima vignette, except with AR and MA models, as well as the order parameter remove returns this error when ```ts.out$sim()``` is run:

 ```
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘qi’ is not a valid field or method name for reference class “Zelig-ma”
```

**Comment by christophergandrud** [comment]
@tercer do you know the status of `sim` for AR and MA models? Was this implemented?

**Comment by mbsabath** [comment]
I did a bit of digging into the issue on a local branch, the issue looks like it has two parts. First, AR and MA only inherit from timeseries, but not from ARIMA, and ARIMA has the qi method causing the initial issue. 

However, even when they do inherit from ARIMA, there are still issues. `sim` doesn't initially throw an error when it's called. But when `summary(ts.out)` is called after running sim, an error is thrown indicating that `qi` is an empty matrix. I haven't been able to find the source of that issue yet.

**Comment by mbsabath** [comment]
Doing a bit more digging into this, it looks like the sim method is also not fully implemented for ARIMA models.

**Comment by christophergandrud** [comment]
Really good digging. I wouldn't be surprised if it hasn't been fully
implemented, qi's for timeseries are really tricky.

At the least in the meantime the docs should flag this issue.

**Comment by mbsabath** [comment]
Sounds good, I made the changes, and am going to push them up to GitHub soon.

**Comment by mbsabath** [comment]
After further investigation, fixing the inheritance issue allows plot to work for the ar and ma methods. The errors that occur after calling summary are still consistent for all of the time series models, and require further investigation.

**Comment by christophergandrud** [comment]
I've taken the `ar` and `ma` models out of the documentation (still needs to filter through the website). They were just (very buggy) wrappers for `arima`. Until they are actually working well, we shouldn't publicise them.

**Comment by christophergandrud** [comment]
Going with `arima` overall syntax. `summary` issue reported separately in https://github.com/IQSS/Zelig/issues/305
