### ISSUE TITLE
Conflict with new version (0.1.0.9000) of pkgdown

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#292]
There appears to be a conflict with the new version (0.1.0.9000) of pkgdown on Hadley's GitHub page or its dependencies. When this is installed, even if it is not loaded (which has really stumped me), if `zelig` is run it returns an error that the formula argument has been unused. So no model is estimated.

Here is an example:

```r
library(Zelig)
library(pkgdown)

z.out <- zelig(gdp_pc ~ trade + civlib, model = "ls", data = a.out)

## Error in gdp_pc ~ trade + civlib : 
## unused arguments (formula = gdp_pc, data = trade + civlib) 
```

**Comment by christophergandrud** [comment]
Initial thought is that the problem might spring from the rlang package. However, the connection is not obvious as having rlang installed and loaded (both from CRAN and version 0.1.1.9000 that is installed by depended on by pkgdown) does not cause the error.

**Comment by christophergandrud** [comment]
It does occur as soon as pkdown is loaded. 

The only way I've found to resolve the issue is to delete all of the non-base packages and reinstall them. Just removing pkdown and its dependencies does not seem to work. This is true even if pkgdown was installed and loaded in `devtools::dev_mode()`.

**Comment by christophergandrud** [comment]
Posted an issue over on pkgdown to see if they have any ideas.

**Comment by izahn** [comment]
I'm able to reliably reproduce this with the development version of `rlang`, and not with the CRAN release of `rlang`. I can even git bisect it to https://github.com/izahn/rlang/commit/529727a355f8688a6a18b15a833071e78e0f2621

Here are the steps you can take to see if you get the same thing as I do:

1. `git clone https://github.com/tidyverse/rlang.git`
2. Start a new R session and run
```
devtools::load_all("~/rlang")
library(Zelig)
zelig(mpg ~ hp, data = mtcars, model = "ls")
```
This should fail with `Error in mpg ~ hp : unused arguments (formula = mpg, data = hp)`.

3. 
```
cd ~/rlang
git checkout HEAD~10
```

4. Repeat step 2. This works for me.

**Comment by izahn** [comment]
Assuming that I'm right about `rlang` being the source of the problem, I can't for the life of me figure out what the problem actually is. It chokes at 

```
    .self$zelig.out <- .self$data %>%
        group_by_(.self$by) %>%
        do(z.out = eval(fn2(.self$model.call,
            quote(as.data.frame(.)))))
```
in the `zelig` method. And now for the weird part: putting a `browser()` call right before that section of code I see the following:
```
> zelig(mpg ~ hp, data = mtcars, model = "ls")
Called from: callSuper(formula = formula, data = data, ..., weights = weights, 
    by = by, bootstrap = bootstrap)
Browse[1]> model.call <- quote(stats::lm(formula = mpg ~ hp, data = mtcars))
Browse[1]> all.equal(model.call, .self$model.call)
[1] TRUE
Browse[1]> .self$data %>%
+     group_by_(.self$by) %>%
+     do(z.out = eval(fn2(model.call,
+                         quote(as.data.frame(.)))))
Source: local data frame [1 x 2]
Groups: <by row>

# A tibble: 1 x 2
     by    z.out
* <dbl>   <list>
1     1 <S3: lm>
Browse[1]> .self$data %>%
+     group_by_(.self$by) %>%
+     do(z.out = eval(fn2(.self$model.call,
+                         quote(as.data.frame(.)))))
Error in mpg ~ hp : unused arguments (formula = mpg, data = hp)
Browse[1]> 
```
So... `model.call` and `.self$model.call` are `all.equal`. But the `do(...)` bit works for one but not the other... very weird.

Unfortunately I can't reproduce this outside of `zelig` at all. I tried along the lines of

```
rcfoo <- setRefClass("model_wrapper",
                     fields = list(model.call = "call",
                                   fn = "ANY",
                                   data = "ANY",
                                   out = "ANY"))

rcfoo$methods(
          initialize = function() {
              .self$fn <- quote(stats::lm)
          })
          
rcfoo$methods(
          fitme = function(formula, data) {
              fn2 <- function(fc, data) {
                  fc$data <- data
                  return(fc)
              }
              .self$model.call <- match.call()
              .self$model.call$formula <- as.Formula(formula)
              .self$model.call[[1]] <- .self$fn
              .self$data <- tbl_df(data)
              .self$data$by <- 1
              .self$data %>%
                  group_by_("by") %>%
               do(bar = eval(fn2(.self$model.call, quote(.))))
          })

              
tst <- rcfoo$new()
tst$fitme(mpg ~ hp, data = mtcars)
```
but I haven't been able to make it fail.

**Comment by christophergandrud** [comment]
Nice work @izahn. (I now realise my problem that I was making the incorrect implicit assumption that switching in and out of `dev_mode` affects the environment.)

The bisect definitely seems to point to the right problem.

I'll move the link to the issue over to rlang.

**Comment by christophergandrud** [comment]
For the time being also, we can get around the pkgdown issue by just reinstalling rlang from CRAN. 

However, having the issue fixed is crucial before the next rlang release as dplyr depends on it. If Zelig effectively doesn't work if a user has dplyr installed, then that is a big problem.

**Comment by christophergandrud** [comment]
A quick response from rlang: https://github.com/tidyverse/rlang/issues/226#issuecomment-319588716

Seems promising that they might work out a solution on their end. . . .

**Comment by christophergandrud** [comment]
Appears to be sorted from the rlang side by https://github.com/tidyverse/rlang/commit/e469466ef75996b89bcc2552ba0e313247d78821
