### ISSUE TITLE
Discrepency between relogit results in Stata and R 

### ISSUE THREAD

**Issue by christophergandrud** [IQSS/Zelig#295]
Original comment at: https://github.com/IQSS/Zelig/issues/88#issuecomment-320387775

**Comment by christophergandrud** [comment]
Sorry @retrography I should have asked earlier, can you provide the data and R code you used to create: https://github.com/IQSS/Zelig/issues/88#issuecomment-320387775

**Comment by christophergandrud** [comment]
After some digging, I don't think the large weighting discrepancy has to do with matrix inversion procedure. 

Here are a number of examples using the *mid* data set included with Zelig:

In Stata:

```
. relogit conflict major contig power maxdem mindem years, wc(0.003430204)


Corrected logit estimates                             Number of obs =     3126

------------------------------------------------------------------------------
             |               Robust
    conflict |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       major |   1.672177   .2775353     6.03   0.000     1.128218    2.216137
      contig |   4.016402   .2288064    17.55   0.000      3.56795    4.464855
       power |   .2883612    .414412     0.70   0.487    -.5238715    1.100594
      maxdem |   .0662866   .0191863     3.45   0.001     .0286822    .1038911
      mindem |  -.0814281   .0298655    -2.73   0.006    -.1399634   -.0228928
       years |  -.1170734    .013316    -8.79   0.000    -.1431723   -.0909745
       _cons |  -6.618889   .3164648   -20.92   0.000    -7.239149    -5.99863
------------------------------------------------------------------------------
```

vs. the two procedures in Zelig (https://github.com/IQSS/Zelig/blob/master/R/model-relogit.R#L259):

```R
## Zelig 5.1-3 implementation
## Qdiag <- lm.influence(lm(y ~ X - 1, weights = W), do.coef = FALSE)$hat / W

z.out1 <- zelig(conflict ~ major + contig + power + maxdem + mindem + years,
                data = mid, model = "relogit", tau = 1042/303772, cite = FALSE,
                case.control = "weighting")
summary(z.out1)

Coefficients:
            Estimate Std. Error z value Pr(>|z|)
(Intercept) -5.97463    1.13971  -5.242 1.59e-07
major        1.69910    0.77375   2.196   0.0281
contig       3.87763    0.73955   5.243 1.58e-07
power        0.32808    1.05690   0.310   0.7562
maxdem       0.06009    0.05088   1.181   0.2376
mindem      -0.04737    0.07342  -0.645   0.5188
years       -0.09634    0.04709  -2.046   0.0408
```

```R
## Old implementation
## Qdiag <- diag(X%*%solve(t(X)%*%diag(W)%*%X)%*%t(X))

Coefficients:
            Estimate Std. Error z value Pr(>|z|)
(Intercept) -5.97463    1.13971  -5.242 1.59e-07
major        1.69910    0.77375   2.196   0.0281
contig       3.87763    0.73955   5.243 1.58e-07
power        0.32808    1.05690   0.310   0.7562
maxdem       0.06009    0.05088   1.181   0.2376
mindem      -0.04737    0.07342  -0.645   0.5188
years       -0.09634    0.04709  -2.046   0.0408
```

Caveat: I'm not sure if the latter is equivalent to the Stata routine. But the following tests provide more evidence that this isn't the cause of the major discrepancy.

There do appear to be two major differences between Zelig and Stata. The first is the calculation of what in Zelig is called `xi` (https://github.com/IQSS/Zelig/blob/master/R/model-relogit.R#L263):

```R
xi <- 0.5 * Qdiag * ((1 + w0) * pihat - w0)
```

This is used to bias correct the coefficients (https://github.com/IQSS/Zelig/blob/master/R/model-relogit.R#L265)

In Stata it's calculated with (on *relogit.ado* line 101):

```
gen `ksi'= .5 * (`sum') * [(1+`wt1')*`pi'-`wt1']
```

Where `w0 = (1 - tau) / (1 - ybar)` and `w1` (`wt1` in Stata) is found with `tau / ybar`.

Using the `w1` (e.g. `wt1`) instead of `w0` in Zelig produces:

```
Coefficients:
            Estimate Std. Error z value Pr(>|z|)
(Intercept) -6.61889    1.13971  -5.808 6.34e-09
major        1.67218    0.77375   2.161   0.0307
contig       4.01640    0.73955   5.431 5.61e-08
power        0.28836    1.05690   0.273   0.7850
maxdem       0.06629    0.05088   1.303   0.1926
mindem      -0.08143    0.07342  -1.109   0.2674
years       -0.11707    0.04709  -2.486   0.0129
```

Now the coefficients are almost identical between Stata and Zelig. However, the standard errors are noticeably different. This is because Stata `relogit` uses robust standard errors by default. If these are not used:

```
. relogit conflict major contig power maxdem mindem years, wc(0.003430204) norobust

Warning: Traditional variance estimates do not make sense
with the wc() option


Corrected logit estimates                             Number of obs =     3126

------------------------------------------------------------------------------
    conflict |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       major |   1.672177   .7720263     2.17   0.030     .1590337    3.185321
      contig |   4.016402    .737902     5.44   0.000     2.570141    5.462664
       power |   .2883612   1.054539     0.27   0.785    -1.778498     2.35522
      maxdem |   .0662866   .0507657     1.31   0.192    -.0332122    .1657855
      mindem |  -.0814281   .0732608    -1.11   0.266    -.2250166    .0621603
       years |  -.1170734   .0469903    -2.49   0.013    -.2091727   -.0249741
       _cons |  -6.618889    1.13717    -5.82   0.000    -8.847701   -4.390077
------------------------------------------------------------------------------
```

Now the standard errors and coefficients are almost identical (using the `lm.influence` matrix inversion routine). 

## Open issues

- why is `xi <- 0.5 * Qdiag * ((1 + w0) * pihat - w0)` used in Zelig rather than the Stata version equivalent `xi <- 0.5 * Qdiag * ((1 + w1) * pihat - w1)`?

- Given the warning produced by Stata relogit when estimating weighted correction without robust standard errors (`Warning: Traditional variance estimates do not make sense
with the wc() option`) and that Zelig doesn't implement robust standard errors, does it make sense to allow weighted correction in Zelig?

**Comment by retrography** [comment]
I haven't got the time to go back to my data and make a sample for you yet, but it seems you have already made a headway on the issue. These are very interesting findings that will probably make me go and revise all the figures in my paper...

One thing I have noticed is that King & Zeng (2001) insist that weighting is the better method when the data is large and there is a possibility of model misspecification. So, I always picked wc by default, and I was surprised when I moved to Zelig and the default was pc. I did not even notice that the robust standard errors were not implemented in Zelig. This warrants a clear explanation in the documentation at least. 

I'm not a statistician, but apparently it is not very difficult to implement the robust standard errors either: https://stats.stackexchange.com/questions/117052/replicating-statas-robust-option-in-r

**Comment by retrography** [comment]
I confirm that with your modification and the robust standard errors explained in the above link, the results from Stata and R is just short of being identical:

Stata:

```stata
. relogit clo col fam_sim desc_sim age_reused size_reused indegree_reused activity_reused, wc(0.0000142020456521824) level(99)


Corrected logit estimates                             Number of obs =   586538

------------------------------------------------------------------------------
             |               Robust
         clo |      Coef.   Std. Err.      z    P>|z|     [99% Conf. Interval]
-------------+----------------------------------------------------------------
         col |   4.292744   .2847105    15.08   0.000     3.559379     5.02611
     fam_sim |     .52282   .0895486     5.84   0.000      .292158     .753482
    desc_sim |   5.763953   .2412736    23.89   0.000     5.142473    6.385433
  age_reused |  -.7684625   .0882528    -8.71   0.000    -.9957867   -.5411382
 size_reused |   .3082039    .020832    14.79   0.000     .2545441    .3618636
indegree_r~d |   .4065681   .0940557     4.32   0.000     .1642968    .6488395
activity_r~d |   .0675615   .0454501     1.49   0.137    -.0495102    .1846332
       _cons |  -11.92239   .1782095   -66.90   0.000    -12.38142   -11.46335
------------------------------------------------------------------------------
```

R:

```R
> coeftest(x$regs$zelig.wc, vcov = vcovHC(x$regs$zelig.wc, "HC1"))

z test of coefficients:

                  Estimate Std. Error   z value              Pr(>|z|)    
(Intercept)     -12.339579   0.098383 -125.4236 < 0.00000000000000022 ***
colTRUE           4.292744   0.284716   15.0773 < 0.00000000000000022 ***
fam_simTRUE       0.522820   0.089550    5.8383        0.000000005274 ***
desc_sim          5.763953   0.241278   23.8892 < 0.00000000000000022 ***
age_reused       -0.768462   0.088255   -8.7073 < 0.00000000000000022 ***
size_reused       0.308204   0.020832   14.7944 < 0.00000000000000022 ***
indegree_reused   0.406568   0.094058    4.3225        0.000015423808 ***
activity_reused   0.067561   0.045451    1.4865                0.1372    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

**Comment by retrography** [comment]
OK, I found it in the paper. See King & Zeng (2001), Page 147, Formula 11. They clearly mention that it is W1 that we use in the calculation of ksi. The Stata version seems to have the right implementation.

**Comment by christophergandrud** [comment]
Thanks for digging into this some more. 

I need to discuss why the changes were made (both to `W1` and removing robust standard errors from Zelig). I know Gary's thinking about the latter has changed, but not sure if the reason for the change is consistent here.

**Comment by retrography** [comment]
Again, I think it is necessary that we add all the reasoning behind the changes to the documentation so that the users know what they are doing. The documentation still refers to the 2001 paper and I have included parts of the explanations in the paper in my thesis, while now I find out that the implementation does not correspond anymore to what I have cited! Rather problematic if you think about it... I'm looking forward to Garry's response on this, as I will be submitting the thesis and the related paper very soon.

Thanks for your great support!

**Comment by christophergandrud** [comment]
Definitely, trying to figure out and document all the undocumented changes
has been a big endeavor.

>

**Comment by christophergandrud** [comment]
Returned the coefficient correction to ISQ 2001, eq 11 in https://github.com/IQSS/Zelig/commit/76eed2d4825a9ef3918f49b6845447eaef6fb1d3

Still thinking about the implementation of robust standard errors, namely should this just be for relogit with weighting or should it be a more general feature.

**Comment by christophergandrud** [comment]
https://github.com/IQSS/Zelig/commit/ef042ad49d004eb3105a0605ca5e96a2c038c166 also applies the robust standard errors for `summary` such that they almost match the Stata version:

```r
Model: 

Call:
relogit(formula = cbind(conflict, 1 - conflict) ~ major + contig + 
    power + maxdem + mindem + years, data = as.data.frame(.), 
    tau = 0.00343020423212146, bias.correct = TRUE, case.control = "weighting")

Deviance Residuals: 
     Min        1Q    Median        3Q       Max  
-0.94933  -0.04958  -0.02173   0.19019   0.48253  

Coefficients:
            Estimate Std. Error (robust) z value Pr(>|z|)    
(Intercept) -6.61889             0.31748 -20.848  < 2e-16 ***
major        1.67218             0.27842   6.006  1.9e-09 ***
contig       4.01640             0.22954  17.498  < 2e-16 ***
power        0.28836             0.41574   0.694 0.487925    
maxdem       0.06629             0.01925   3.444 0.000573 ***
mindem      -0.08143             0.02996  -2.718 0.006572 ** 
years       -0.11707             0.01336  -8.764  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 143.116  on 3125  degrees of freedom
Residual deviance:  91.178  on 3119  degrees of freedom
AIC: 27.041

Number of Fisher Scoring iterations: 10
```

compared to Stata:

```
. relogit conflict major contig power maxdem mindem years, wc(0.003430204)


Corrected logit estimates                             Number of obs =     3126

------------------------------------------------------------------------------
             |               Robust
    conflict |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       major |   1.672177   .2775353     6.03   0.000     1.128218    2.216137
      contig |   4.016402   .2288064    17.55   0.000      3.56795    4.464855
       power |   .2883612    .414412     0.70   0.487    -.5238715    1.100594
      maxdem |   .0662866   .0191863     3.45   0.001     .0286822    .1038911
      mindem |  -.0814281   .0298655    -2.73   0.006    -.1399634   -.0228928
       years |  -.1170734    .013316    -8.79   0.000    -.1431723   -.0909745
       _cons |  -6.618889   .3164648   -20.92   0.000    -7.239149    -5.99863
```

Still need to implement for `sim`

**Comment by christophergandrud** [comment]
Should now be sorted in https://github.com/IQSS/Zelig/commit/b3d3e5997ac72fead1d088ea4fc25343edf5d463 including for `sim`

**Comment by retrography** [comment]
@christophergandrud I know this issue is already closed and I don't want to repopen it. But I really have to thank you for verifying and rectifying the issue.

**Comment by christophergandrud** [comment]
No worries @retrography. Thanks for reporting and all of your work on this!

**Comment by retrography** [comment]
@christophergandrud There is an issue here. If I call relogit through the zelig function the robust standard errors, and odds ratios work. If I call relogit directly, non works.

**Comment by christophergandrud** [comment]
Hm, I'll look into it.

In the meantime, please use `from_zelig_model`, e.g.:

```r
library(stargazer)
library(Zelig)

data(mid)
z.out1 <- zelig(conflict ~ major + contig + power + maxdem + mindem + years,
                data = mid, model = "relogit", tau = 1042/303772)

from_zelig_model(z.out1) %>% stargazer()
```

**Comment by retrography** [comment]
@christophergandrud No, it actually doesn't work, because it returns the results from the relogit function, so you get the same old. See below.

```R
  itr$regs$zelig.wc <- from_zelig_model(
    zelig(
      fun ~ col + fam_sim + desc_sim + age_reused + size_reused + indegree_reused + activity_reused,
      data = sample,
      tau = itr$tau,
      model = "relogit",
      case.control = "weighting",
      bias.correct = T,
      cite = F
    )
  )

summary(x$regs$zelig.wc)
```
Gets you:

```
Call:
relogit(formula = cbind(fun, 1 - fun) ~ col + fam_sim + desc_sim + 
    age_reused + size_reused + indegree_reused + activity_reused, 
    data = as.data.frame(.), tau = 9.16999274066485e-05, bias.correct = TRUE, 
    case.control = "weighting")

Deviance Residuals: 
     Min        1Q    Median        3Q       Max  
-1.17312  -0.00791  -0.00635  -0.00570   0.81701  

Coefficients:
                 Estimate Std. Error z value Pr(>|z|)    
(Intercept)     -10.59231    0.21980 -48.190  < 2e-16 ***
colTRUE           2.41716    0.40564   5.959 2.54e-09 ***
fam_simTRUE       0.11727    0.22208   0.528   0.5975    
desc_sim          3.38383    0.74293   4.555 5.25e-06 ***
age_reused       -0.14672    0.08579  -1.710   0.0872 .  
size_reused      -0.08268    0.08930  -0.926   0.3545    
indegree_reused   1.13638    0.07614  14.925  < 2e-16 ***
activity_reused   0.14772    0.06719   2.199   0.0279 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1791.6  on 948704  degrees of freedom
Residual deviance: 1306.6  on 948697  degrees of freedom
AIC: 190.5

Number of Fisher Scoring iterations: 13
```

**Comment by christophergandrud** [comment]
Yes, you don't get the odds ratios, that doesn't work yet. You have to manually add them to the output of `from_zelig_model(z.out1)`.

**Comment by retrography** [comment]
@christophergandrud The problem is not the odds ratios. Compare the two results above. What is missing is the robust standard errors. I am actually using the `from_zelig_model` function for the second one.

**Comment by christophergandrud** [comment]
Yes none of it is working. I won't have time to get to this for awhile, so in the meantime if you want to use this function with a separate package you would have to extract the basic estimation and hack your way to the rest.  :)

**Comment by retrography** [comment]
@christophergandrud That's why I am doing right now.

**Comment by christophergandrud** [comment]
Sorry for the inconvenience and thanks for reporting these issues!
