### ISSUE TITLE
Broken menu link in webpage

### ISSUE THREAD

**Issue by cchoirat** [IQSS/Zelig#301]
In https://zeligproject.org/, menu item `Software -> Download` points to http://docs.zeligproject.org/en/latest/installation_quickstart.html#installing-r-and-zelig, which doesn't exist anymore.  Page seems to have been removed from the new docs http://docs.zeligproject.org/index.html.

**Comment by mbsabath** [comment]
Odd that the automated link checker missed this. Do you or @christophergandrud where in the project the main website page lives? We could be missing a directory with out checker.

**Comment by mbsabath** [comment]
Nevermind, looks like the initial landing page exists outside of the automatically generated documentation. That explains why we're not seeing it with the checker and missed it during our initial work.

**Comment by christophergandrud** [comment]
I've updated the link to: http://docs.zeligproject.org/articles/quickstart.html#installing-and-loading-zelig

However it doesn't seem to have propagated from the OpenScholar interface to the deployed site yet. Will check later
