### ISSUE TITLE
sim() error with differenced first-order autoregressive model 

### ISSUE THREAD

**Issue by nmbrodnax** [IQSS/Zelig#307]
```r
library(Zelig)
library(magrittr)

data(seatshare)
subset <- seatshare[seatshare$country == "UNITED KINGDOM",]

s.out <- zelig(unemp ~ leftseat, data = subset, model = "arima",
               order = c(1,1,0)) %>%
    setx(leftseat = 0.25) %>%
    setx1(leftseat = 0.75) %>%
    sim()
```

produces 

`Error in apply(beta, 2, mean) : dim(X) must have a positive length`

I was able to reproduce this error with different data and different `setx()` parameters

**Comment by christophergandrud** [comment]
(Just for documentation purposes) noting that this seems similar to, but different from https://github.com/IQSS/Zelig/issues/305.

**Comment by christophergandrud** [comment]
Does this commit resolve the issue: 3b5c71df030325a74beea9858ede44c0fed4b743?

**Comment by nmbrodnax** [comment]
Yes, everything works on my end.
