### ISSUE TITLE
Tobit vignette should mention that Zelig uses AER

### ISSUE THREAD

**Issue by izahn** [IQSS/Zelig#315]
The "See also" section of the `zelig-tobit` vignette refers readers to the `survfit` function in the `survival` package. Since it actually wraps `AER::tobit` it should refer readers there instead.

**Comment by christophergandrud** [comment]
Good idea. 

Done in 5d55f26cc0c2593e4bda804086a3bb4631a53512. Will be applied to the live site on the next build for the next release.
