### ISSUE TITLE
get_predict()

### ISSUE THREAD

**Issue by VahidTehrani** [IQSS/Zelig#320]
It looks something is not right in the `get_predict()` function. 

```
data(mid)
z.out1 <- zelig(conflict ~ major + contig + power + maxdem + mindem + years,
                data = mid, model = "relogit", tau = 1042/303772)
prob <- z.out1$get_predict()
max(sapply(prob, max))
min(sapply(prob, min))
```

and return 0.9610796 as max and -10.59513 as min. Does it make sense? It supposed to be probability!! The link fucntion is 'logit'.

**Comment by christophergandrud** [comment]
Thanks for reporting @VahidTehrani. I'll take a look.

**Comment by christophergandrud** [comment]
I think it's because currently the `type` argument to `predict` is not set as `response`.  Not great use-ability for this case, so I'll work on a better solution. 

In the mean time:

```r
library(zeligverse)
data(mid)
z.out1 <- zelig(conflict ~ major + contig + power + maxdem + mindem + years,
                data = mid, model = "relogit", tau = 1042/303772)

# Extract fitted model object and predict response probabilities
fitted_model <- from_zelig_model(z.out1)
prob <- predict(fitted_model, type = "response")

max(sapply(prob, max))
min(sapply(prob, min))
```

**Comment by christophergandrud** [comment]
From 971809eabd7448b2456b4917247bd1083fb1dd1f `predict` accepts arguments (like `type = "response"`)

**Comment by VahidTehrani** [comment]
Thanks! @christophergandrud

**Comment by retrography** [comment]
Is it normal that the predicted probabilities for the relogit are always by two levels of magnitude smaller than those of the regular logit?

    predict(logit.reg, test, type="response")[[1]]
    # 0.03674828 
    predict(relogit.reg, test, type="response")[[1]]
    # 0.0003176832
