### ISSUE TITLE
ordered logistic regression deprecated?

### ISSUE THREAD

**Issue by juliosolisar** [IQSS/Zelig#346]
impossible to replicate http://docs.zeligproject.org/articles/zeligchoice_ologit.html 

```
data(sanction)
sanction$ncost <- factor(sanction$ncost, ordered = TRUE,
                         levels = c("net gain", "little effect", "modest loss", "major loss"))
z.out <- zelig(ncost ~ mil + coop, model = "ologit",
               data = sanction)
```

**Comment by joannieboire** [comment]
@juliosolisar I had the same problem. I noticed that Zelig was not actually installing the ZeligChoice dependency as it should. So I just installed the ZeligChoice package from the CRAN archive myself, and now it works.

**Comment by juliosolisar** [comment]
thanks @joannieboire !
