### ISSUE TITLE
Track community usage

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/Zelig#54]
Post question to user when Zelig is used interactively:
"could you opt in to provide usage stats to improve Zelig?"
- Ask to opt in at install time.

**Comment by christophergandrud** [comment]
RStudio CRAN downloads dashboard available at: https://iqss.github.io/rpackagemetrics/ (will also be linked to from the upcoming new Zelig site).

Still need more thought on the individual function stats. But I'll close this issue for the time being.
