### ISSUE TITLE
GIM Test improvement

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/Zelig#77]
Gary will follow up with Molly for a better estimate.

**Comment by tercer** [comment]
Ratio test criteria defined as 1.5, from Molly.

**Comment by mcrosas** [comment]
Show  draft of the output to @thegaryking

**Comment by thegaryking** [comment]
i'd still like to see version 2.  here's my current version:
https://docs.google.com/document/d/16ilzsJKJfS8Sa_BERDHJ8ASWCfEYKeS1olbqqtanAa8/edit

**Comment by mcrosas** [comment]
Assigning to @cchoirat to review output with @thegaryking

**Comment by christophergandrud** [comment]
I believe Mark Hill has just started creating a package to do much of this. Will work with him to integrate it with Zelig.

**Comment by christophergandrud** [comment]
I believe Mark Hill has ambitions for that package which would also impact https://github.com/IQSS/Zelig/issues/140

**Comment by christophergandrud** [comment]
This will be in https://github.com/IQSS/RobustSE

Need to work on Zelig integration once RobustSE is releasable.
