### ISSUE TITLE
Documentation for GIM test

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/Zelig#82]
To add in Zelig Documentation: a short description about the GIM test, as it is used in Zelig, plus a reference to the GIM paper.

**Comment by christophergandrud** [comment]
Related to: https://github.com/IQSS/Zelig/issues/77

**Comment by christophergandrud** [comment]
This will be in https://github.com/IQSS/RobustSE 

Need to work on Zelig integration once RobustSE is releasable.
