### ISSUE TITLE
Bug when using `update` in `ztobit`

### ISSUE THREAD

**Issue by MichaelChirico** [IQSS/Zelig#87]
Something is going wrong when using an implicit formula definition within a call to a `zelig-tobit` model.

Using the [documented example](http://docs.zeligproject.org/en/latest/zelig-tobit.html) (by the way, that page needs to be updated to Z5 architecture) works fine:

```
z5<-ztobit$new()
z5$zelig(durable~age+quant,data=tobin)
```

However, if we wish to define the formula implicitly (which is done often, e.g., [when we are running different specifications of controls and updating as we go along](http://stackoverflow.com/questions/27847373/using-a-defined-set-of-controls-for-many-regressions-in-r)), we get an error:

```
controls<- ~quant
z5$zelig(update(controls,durable~age+.),data=tobin)
```

Gives error:

```
Error in terms.formula(formula, special, data = data) : 
  'data' argument is of the wrong type
```

Here's the call stack:

> traceback()
> 24: terms.formula(formula, special, data = data)
> 23: terms(formula, special, data = data)
> 22: terms(formula, special, data = data)
> 21: survreg(formula = Surv(ifelse(durable <= 0, 0, durable), durable > 
>         0, type = "left") ~ age + quant, data = as.data.frame(.), 
>         dist = "gaussian")
> 20: eval(expr, envir, enclos)
> 19: eval(cl, oenv)
> 18: AER::tobit(formula = update(controls, durable ~ age + .), data = as.data.frame(.), 
>         left = 0, right = Inf)
> 17: eval(expr, envir, enclos)
> 16: eval(fn2(.self$model.call, quote(as.data.frame(.))))
> 15: eval(expr, envir, enclos)
> 14: eval(args[[j]]$expr, envir = env)
> 13: do_.grouped_df(.data, .dots = lazyeval::lazy_dots(...))
> 12: do_(.data, .dots = lazyeval::lazy_dots(...))
> 11: do(., z.out = eval(fn2(.self$model.call, quote(as.data.frame(.)))))
> 10: function_list[[k]](value)
> 9: withVisible(function_list[[k]](value))
> 8: freduce(value, `_function_list`)
> 7: `_fseq`(`_lhs`)
> 6: eval(expr, envir, enclos)
> 5: eval(quote(`_fseq`(`_lhs`)), env, env)
> 4: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 3: .self$data %>% group_by_(.self$by) %>% do(z.out = eval(fn2(.self$model.call, 
>        quote(as.data.frame(.)))))
> 2: callSuper(formula = formula, data = data, ..., by = by)
> 1: z5$zelig(update(controls, durable ~ age + .), data = tobin)

Seems the source is in what's getting passed to `AER::tobit`--I don't know what it thinks `.` is, but simply running `AER::tobit(update(controls,durable~age+.),data=tobin)` causes no issues. Not sure where in the source this line of code is (it seems its kicked off in `model-zelig.R`), but could just need to be updated to `data=data`--perhaps it's confusing the `.` used somewhere else in the code with that introduced by `update`.

Note that this isn't an issue with, say, `zelig-ls`:

```
z5.2<-zls$new()
z5.2$zelig(update(controls,durable~age+.),data=tobin)
```

Or `zelig-logit`:

```
z5.3<-zlogit$new()
z5.3$zelig(update(controls,I(durable>0)~age+.),data=tobin)
```

The `update` bit wouldn't seem to be the problem, as that call by itself gives exactly what we expect:

```
update(controls,durable~age+.)
> update(controls,durable~age+.)
durable ~ age + quant
```

**Comment by christophergandrud** [comment]
That is strange. In version 5.0-15 when I now get the error:

```r
library(Zelig)
data(tobin)
  
z5<-ztobit$new()
z5$zelig(durable~age+quant,data=tobin)
controls<- ~quant
z5$zelig(update(controls, durable ~ age + .), data = tobin)

## Error in eval(expr, envir, enclos) : could not find function "survreg"
```

Not sure why the `update` prompts the survreg function such that it isn't in the environment. When I manually load *survival* the error is then:

```r
## Error in as.data.frame(.) : object '.' not found
```

**Comment by christophergandrud** [comment]
I have a working solution in this branch: https://github.com/IQSS/Zelig/tree/dotformula

Download it with:

```r
devtools::install_github("IQSS/Zelig", ref = "dotformula")
```

I haven't merged it into master yet, however, because the solution seems to interfere with relogit. Will keep working on this.

Issue also related to: https://github.com/IQSS/Zelig/issues/244

**Comment by christophergandrud** [comment]
Merge into master in b6a7a3a6124a57eb4a121ddc10d04d85153826ce
