### ISSUE TITLE
Relogit extremely slow

### ISSUE THREAD

**Issue by retrography** [IQSS/Zelig#88]
I have moved to R from Stata and I am trying to run some `relogit` regressions in R. My data is rather large (in order of tens or hundreds of thousands of observations). I have noticed that it takes an extremely long time (above ten minutes) to run the exact same regressions that would run under Stata in a matter of seconds. I wonder what turns the code so slow here, to this impractical level. I had a look at the R code, and I found a `for` loop over the columns that can be pretty slow. Maybe there are parts of the code that can benefit from parallelization as well - I suppose that is one thing Stata already does by default.

**Comment by christophergandrud** [comment]
The issue appears to be at the `lm.influence` call on line [168](https://github.com/IQSS/Zelig/blob/eaf0484c8bff179c8b2dd8a44828cee1cc35bc0e/R/model-relogit.R#L168) in the `relogit` function. Here's the profile using 100,000 simulated observations. 

![screen shot 2017-01-30 at 14 49 06](https://cloud.githubusercontent.com/assets/1285805/22438794/492d4984-e6fb-11e6-8ca2-cc8d99d569f9.png)
 
This is much slower than using `logit`.

The issue seems to be within `lm.influence`. So I think to speed this up we might need to rewrite this function.

**Comment by christophergandrud** [comment]
Further narrowing it down, it looks like within `lm.influence` most of the hold up is at:

```R
res <- .Call(stats:::C_influence, mqr, do.coef, e, tol)
```

![screen shot 2017-01-30 at 15 03 38](https://cloud.githubusercontent.com/assets/1285805/22439395/737d5a74-e6fd-11e6-8f13-f04b1706c548.png)

**Comment by christophergandrud** [comment]
I think this means that we would need to rewrite the C code behind C_influence

**Comment by retrography** [comment]
Since this seems to be a fundamental issue and has taken long to address, I would like to suggest a temporary work around for those users who are affected. I use RStata to run my relogits in Stata while all the data steps and the rest of my analysis are in R. 

Here is how it works:

```R
require(RStata)
options(RStata.StataVersion = 14)
options(RStata.StataPath = "/Applications/Stata/StataSE.app/Contents/MacOS/stata-se")
stata(src = "relogit depvar indepvar1 indepvar2", data.in = df)
```
This takes its data from your data frames and returns the results within the R interface, so there is no need for saving and reloading dta files, etc...

**Comment by retrography** [comment]
I have to add here that the estimates from the Weighted correction method are fundamentally different from those of the same model on Stata at least for very rare events.

**Comment by retrography** [comment]
@christophergandrud Or you need to go back to the old matrix inversion routine used in Stata. See my post above. One or the other software is going very wrong in its estimations, and I won't bet my money on the R implementation.

**Comment by retrography** [comment]
@christophergandrud I fixed the performance issue in #294. No need to rewrite the C code. But major differences in the estimates (between R and Stata when using the Weighting method) persist. Zelig's reference manual does point out possible "slight" differences, but what I observe is much more than a slight difference. Neither the size of the estimates nor their significance is anywhere close to each other.

**Comment by christophergandrud** [comment]
Thanks for the update. It might be good to loop in @cchoirat as I think she may have a better sense of what's going on (I think from looking at the git history that she did most of the coding on it).

**Comment by cchoirat** [comment]
Actually, it was ported from Zelig 4.  Happy to look into it though.

**Comment by retrography** [comment]
@cchoirat If you can't reproduce the issue, I can provide a sample dataset, but I suspect any sample dataset would do. And don't forget to apply #294 before running Zelig's relogit function on a large dataset. Will save you hours!

**Comment by retrography** [comment]
@christophergandrud Probably it is a good idea to open a new issue for this discussion, because the performance issue is already fixed.

**Comment by christophergandrud** [comment]
Yeah, @cchoirat I had a feeling that was the case. Any idea who the original author was?

**Comment by christophergandrud** [comment]
Good idea @retrography on a new issue.

**Comment by cchoirat** [comment]
No, but it seems it was already available in Zelig 3 (
https://r.iq.harvard.edu/docs/zelig.pdf, p. 493).  Maybe @tercer knows more
about the model history?
