### ISSUE TITLE
Dealing with accidental variable misnaming

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#94]
It would be helpful to implement a number of checks against simple errors in specifying the arguments that maybe common.  For example, adding a variable name in a formula, which is not present in the dataset gives an unintuitive error message:
<img width="663" alt="screen shot 2015-10-01 at 10 22 16 pm" src="https://cloud.githubusercontent.com/assets/2085037/10238256/322b1c06-688b-11e5-8fb0-7aea6d21a7e0.png">
While common in R, we could check against such things and provide some suggestions and guidance.

**Comment by christophergandrud** [comment]
Related to https://github.com/IQSS/Zelig/issues/160
