### ISSUE TITLE
summary method: print method for summary of Zelig output contains options elements

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#96]
We use options() to change some of R's defaults for summary and printing, so as to use the original summary methods for wrapped models.  For "summary(z.out)" this works fine:
![screen shot 2015-10-02 at 3 49 48 pm](https://cloud.githubusercontent.com/assets/2085037/10256214/bf427890-691d-11e5-8518-73d9b49b3f26.png)

But for "print(summary(z.out))" the options are added to the object and printed as:

![screen shot 2015-10-02 at 3 50 44 pm](https://cloud.githubusercontent.com/assets/2085037/10256209/b2713746-691d-11e5-9365-48719fa210a5.png)

**Comment by christophergandrud** [comment]
Appears not to be a problem any more:

```r
library(Zelig)
data(macro)
z.out1 <- zelig(unem ~ gdp + capmob + trade, model = "ls", data = macro,
                cite = FALSE
summary(z.out1)
Model: 

Call:
z5$zelig(formula = unem ~ gdp + capmob + trade, data = macro)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.3008 -2.0768 -0.3187  1.9789  7.7715 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept)  6.181294   0.450572  13.719  < 2e-16
gdp         -0.323601   0.062820  -5.151 4.36e-07
capmob       1.421939   0.166443   8.543 4.22e-16
trade        0.019854   0.005606   3.542 0.000452

Residual standard error: 2.746 on 346 degrees of freedom
Multiple R-squared:  0.2878,	Adjusted R-squared:  0.2817 
F-statistic: 46.61 on 3 and 346 DF,  p-value: < 2.2e-16

Next step: Use 'setx' method
```
